[package]
name = "dicom-dictionary-std"
version = "0.1.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
edition = "2015"

[dependencies]
dicom-core = { path = "../core" }
lazy_static = "1.2.0"
