[package]
name = "dicom-dictionary-std"
version = "0.1.0-pre.1"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "Standard DICOM attribute dictionary"
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Enet4/dicom-rs"
keywords = ["dicom"]

[dependencies]
dicom-core = { path = "../core" }
lazy_static = "1.2.0"
