language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - TEST_DIR=core
  - TEST_DIR=dictionary_builder
script: cd $TEST_DIR && cargo test
matrix:
  allow_failures:
    - rust: 
      - beta
      - nightly
