language: rust

matrix:
  include:
   - rust: stable
     env: CLIPPY=1
   - rust: beta
   - rust: nightly
     env: CLIPPY=1
  allow_failures:
    - rust: nightly

before_script:
  - if [ "$CLIPPY" ]; then
      (rustup component add clippy || rustup component add clippy-preview) && CLIPPY_INSTALLED=1 || CLIPPY_INSTALLED=0;
    fi

script:
  - cargo build --all
  - if [ "$CLIPPY_INSTALLED" == 1 ]; then
      cargo clippy;
    fi
  # default features
  - cargo test --all
  # no inventory
  - cargo test --manifest-path encoding/Cargo.toml --no-default-features
  - cargo test --manifest-path transfer-syntax-registry/Cargo.toml --no-default-features
