[package]
name = "dicom-object"
version = "0.1.0-pre.1"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
edition = "2018"

[dependencies]
dicom-core = { path = "../core" }
dicom-parser = { path = "../parser" }
dicom-dictionary-std = { path = "../dictionary-std/" }
itertools = "0.8.0"
byteordered = "0.4.0"
smallvec = "0.6.7"
