[package]
name = "dicom-object"
version = "0.1.0-pre.1"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Enet4/dicom-rs"

[dependencies]
dicom-core = { path = "../core" }
dicom-encoding = { path = "../encoding" }
dicom-parser = { path = "../parser" }
dicom-dictionary-std = { path = "../dictionary-std" }
dicom-transfer-syntax-registry = { path = "../transfer-syntax-registry" }
itertools = "0.8.0"
byteordered = "0.4.0"
smallvec = "0.6.7"
