[package]
name = "dicom-dump"
version = "0.5.0-rc.2"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A CLI tool for inspecting DICOM files"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
categories = ["command-line-utilities"]
keywords = ["cli", "dicom", "dump"]
readme = "README.md"

[lib]
name = "dicom_dump"
path = "src/lib.rs"

[[bin]]
name = "dicom-dump"
path = "src/main.rs"
required-features = ["cli"]

[features]
default = ["cli"]
cli = ["structopt", "dicom-transfer-syntax-registry/inventory-registry", "dicom-object/backtraces"]

[dependencies]
term_size = "0.3.2"
itertools = "0.10"
snafu = "0.7.0"
colored = "2.0.0"
structopt = { version = "0.3.21", optional = true }
dicom-core = { path = "../core" }
dicom-encoding = { path = "../encoding" }
dicom-object = { path = "../object/" }
dicom-transfer-syntax-registry = { path = "../transfer-syntax-registry/" }
dicom-dictionary-std = { path = "../dictionary-std/" }

