[package]
name = "dicom-core"
version = "0.1.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "Efficient and practical core library for DICOM compliant systems"
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Enet4/dicom-rs"
keywords = ["dicom"]

[badges]

[badges.travis-ci]
repository = "Enet4/dicom-rs"

[dependencies]
chrono = "0.4.6"
itertools = "0.8.0"
quick-error = "1.2.2"
smallvec = "1.0.0"
