[package]
name = "dicom-parser"
version = "0.1.0-pre.1"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A mid-level parser of DICOM data"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"

[dependencies]
dicom-core = { path = "../core" }
dicom-encoding = { path = "../encoding" }
quick-error = "1.2.2"
chrono = "0.4.6"
dicom-dictionary-std = { path = "../dictionary-std/" }
smallvec = "0.6.7"
