[package]
name = "dicom"
version = "0.1.0-pre.1"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A pure Rust implementation of the DICOM standard"
edition = "2018"
publish = false
license = "Apache-2.0 OR MIT"
repository = "https://github.com/Enet4/dicom-rs"

[badges]

[badges.travis-ci]
repository = "Enet4/dicom-rs"

[dependencies]
dicom-core = { path = "../core" }
dicom-dictionary-std = { path = "../dictionary-std" }
dicom-encoding = { path = "../encoding" }
dicom-parser = { path = "../parser" }
dicom-transfer-syntax-registry = { path = "../transfer-syntax-registry" }
dicom-object = { path = "../object" }
