[package]
name = "dicom-encoding"
version = "0.1.0-pre.1"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "DICOM encoding and decoding primitives"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
categories = ["encoding"]
keywords = ["dicom"]

[dependencies]
dicom-core = { path = "../core" }
dicom-dictionary-std = { path = "../dictionary-std" }
quick-error = "1.2.2"
encoding = "0.2.33"
byteordered = "0.4.0"
inventory = "0.1.4"
