[package]
name = "dicom-encoding"
version = "0.2.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "DICOM encoding and decoding primitives"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
categories = ["encoding"]
keywords = ["dicom"]
readme = "README.md"

[badges.travis-ci]
repository = "Enet4/dicom-rs"

[features]
default = []
inventory-registry = ['inventory']

[dependencies]
dicom-core = { path = "../core", version = "0.2.0" }
dicom-dictionary-std = { path = "../dictionary-std", version = "0.2.0" }
quick-error = "1.2.3"
encoding = "0.2.33"
byteordered = "0.5.0"
inventory = { version = "0.1.4", optional = true }
