[package]
name = "dicom-fromimage"
version = "0.1.0"
edition = "2018"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A CLI tool for replacing the image content from DICOM files"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
categories = ["command-line-utilities"]
keywords = ["cli", "dicom", "image", "image-conversion"]
readme = "README.md"

[features]
default = ['dicom-object/inventory-registry', 'dicom-object/backtraces']

[dependencies]
dicom-core = { path = "../core" }
dicom-dictionary-std = { path = "../dictionary-std/" }
dicom-object = { path = "../object/" }
snafu = "0.7.0"
structopt = "0.3.23"

[dependencies.image]
version = "0.24.1"
default-features=false
features = ["jpeg", "png", "pnm", "tiff", "webp", "bmp", "jpeg_rayon"]
