[package]
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A generator of DICOM data dictionaries"
license = "MIT/Apache-2.0"
name = "dicom-dictionary-builder"
publish = false
version = "0.1.0"
repository = "https://github.com/Enet4/dicom-rs"

[[bin]]
name = "dictionary-builder"
path = "main.rs"

[dependencies]
clap = "2.18.0"
futures = "~0.1.21"
hyper = "0.11.6"
quick-xml = "0.12.1"
regex = "1.0.0"
serde = "1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.17"
tokio-core = "0.1.10"
