[package]
name = "dicom-storescu"
version = "0.2.0-rc.2"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
description = "A DICOM C-ECHO command line interface"
categories = ["command-line-utilities"]
keywords = ["dicom"]
readme = "README.md"

[dependencies]
dicom-ul = { path = '../ul', version = "0.4.0-rc.2" }
dicom = { path = '../parent', version = "0.5.0-rc.2" }
structopt = "0.3.21"
walkdir = "2.3.2"
indicatif = "0.16.2"
