[package]
name = "dicom-transfer-syntax-registry"
version = "0.1.0-pre.1"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A registry of DICOM transfer syntaxes"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"

[dependencies]
dicom-core = { path = "../core" }
dicom-encoding = { path = "../encoding" }
lazy_static = "1.2.0"
encoding = "0.2.33"
byteordered = "0.4.0"
inventory = "0.1.4"
