[package]
name = "dicom-transfer-syntax-registry"
version = "0.4.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A registry of DICOM transfer syntaxes"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
keywords = ["dicom"]
readme = "README.md"

[features]
default = []
inventory-registry = ['dicom-encoding/inventory-registry', 'inventory']

[dependencies]
dicom-core = { path = "../core", version = "0.4.0" }
dicom-encoding = { path = "../encoding", version = "0.4.0" }
lazy_static = "1.2.0"
encoding = "0.2.33"
byteordered = "0.5.0"
inventory = { version = "0.1.4", optional = true }
